import type { RawTender, TenderSource } from './types';

const MOCK_TENDERS: RawTender[] = [
  {
    externalId: 'MOCK-001',
    title: 'Byggledning för nyproduktion av bostäder i Hagastaden',
    description: 'Stockholms stad söker byggledare för nyproduktion av 120 lägenheter i Hagastaden. Uppdraget omfattar byggledning genom samtliga skeden från projektering till slutbesiktning. Erfarenhet av flerbostadshus och komplexa stadsmiljöer krävs. BIM-samordning ingår.',
    category: 'byggledning',
    region: 'Stockholm',
    buyer: 'Stockholms stad',
    value: 4500000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 2 * 86400000),
    deadlineAt: new Date(Date.now() + 12 * 86400000),
    source: 'mercell',
    sourceUrl: 'https://mercell.com/mock/001',
    rawData: { cpvCode: '71520000', lotNumber: 1 },
  },
  {
    externalId: 'MOCK-002',
    title: 'Kontrollansvarig (KA) för skolbyggnad i Mölndal',
    description: 'Mölndals kommun upphandlar kontrollansvarig enligt PBL för ombyggnad och tillbyggnad av Fässbergsskolan. Projektet värderas till ca 80 Mkr. KA ska medverka vid tekniska samråd, arbetsplatsbesök och slutsamråd.',
    category: 'kontrollansvarig',
    region: 'Göteborg',
    buyer: 'Mölndals kommun',
    value: 800000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 1 * 86400000),
    deadlineAt: new Date(Date.now() + 4 * 86400000),
    source: 'visma_anbud',
    sourceUrl: 'https://vismaanbud.com/mock/002',
    rawData: { referenceNumber: 'VA-2024-1234' },
  },
  {
    externalId: 'MOCK-003',
    title: 'Projektering av VA-nät i Uppsala kommun',
    description: 'Uppsala Vatten söker konsult för projektering av nytt VA-nät i Södra staden. Omfattar ca 5 km ledningssträcka, pumpstationer och dagvattenhantering. Geoteknisk utredning ska inkluderas.',
    category: 'projektering',
    region: 'Uppsala',
    buyer: 'Uppsala Vatten och Avfall AB',
    value: 3200000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 5 * 86400000),
    deadlineAt: new Date(Date.now() + 20 * 86400000),
    source: 'ted_eu',
    sourceUrl: 'https://ted.europa.eu/mock/003',
    rawData: { tedReference: '2024/S 045-123456' },
  },
  {
    externalId: 'MOCK-004',
    title: 'Besiktning av broar och tunnlar i Västra Götaland',
    description: 'Trafikverket Region Väst upphandlar besiktningstjänster för ca 200 broar och 15 tunnlar. Ramavtal 4 år. Kräver certifierad brobesiktningsman med minst 5 års erfarenhet.',
    category: 'besiktning',
    region: 'Göteborg',
    buyer: 'Trafikverket',
    value: 8000000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 3 * 86400000),
    deadlineAt: new Date(Date.now() + 30 * 86400000),
    source: 'mercell',
    sourceUrl: 'https://mercell.com/mock/004',
    rawData: { cpvCode: '71631400', framework: true },
  },
  {
    externalId: 'MOCK-005',
    title: 'Mark och exploatering — detaljplan Västerås',
    description: 'Västerås stad söker konsultstöd för mark- och exploateringsfrågor kopplat till ny detaljplan för Öster Mälarstrand. Uppdraget inkluderar exploateringsavtal, markvärdering och samordning med byggherrar.',
    category: 'mark_exploatering',
    region: 'Västerås',
    buyer: 'Västerås stad',
    value: 1500000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 0.5 * 86400000),
    deadlineAt: new Date(Date.now() + 8 * 86400000),
    source: 'visma_anbud',
    sourceUrl: 'https://vismaanbud.com/mock/005',
    rawData: { referenceNumber: 'VA-2024-5678' },
  },
  {
    externalId: 'MOCK-006',
    title: 'Geoteknisk undersökning Norrköping',
    description: 'Norrköpings kommun upphandlar geoteknisk undersökning och markmiljöutredning inför nybyggnad av idrottshall. Inkluderar provtagning, laboratorieanalys, grundläggningsrekommendationer och riskbedömning avseende förorenad mark.',
    category: 'geoteknik',
    region: 'Norrköping',
    buyer: 'Norrköpings kommun',
    value: 650000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 1 * 86400000),
    deadlineAt: new Date(Date.now() + 15 * 86400000),
    source: 'mercell',
    sourceUrl: 'https://mercell.com/mock/006',
    rawData: { cpvCode: '71332000' },
  },
  {
    externalId: 'MOCK-007',
    title: 'BIM-samordning för sjukhusbyggnad Malmö',
    description: 'Region Skåne söker BIM-samordnare för tillbyggnad av Skånes universitetssjukhus. Projektet är ett av regionens största bygginvesteringar. Konsulten ska säkerställa BIM-krav enligt BEAst och ansvara för modellsamordning i alla projektskeden.',
    category: 'bim_samordning',
    region: 'Malmö',
    buyer: 'Region Skåne',
    value: 2800000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 4 * 86400000),
    deadlineAt: new Date(Date.now() + 25 * 86400000),
    source: 'ted_eu',
    sourceUrl: 'https://ted.europa.eu/mock/007',
    rawData: { tedReference: '2024/S 050-654321' },
  },
  {
    externalId: 'MOCK-008',
    title: 'Rivning och sanering av industrilokal Helsingborg',
    description: 'Helsingborgs stad upphandlar entreprenör för rivning och sanering av f.d. kemikaliefabrik. Uppdraget kräver erfarenhet av miljösanering, asbesthantering och kontrollplan enligt PBL.',
    category: 'rivning_sanering',
    region: 'Helsingborg',
    buyer: 'Helsingborgs stad',
    value: 12000000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 7 * 86400000),
    deadlineAt: new Date(Date.now() + 3 * 86400000),
    source: 'mercell',
    sourceUrl: 'https://mercell.com/mock/008',
    rawData: { cpvCode: '45111000', hazardous: true },
  },
  {
    externalId: 'MOCK-009',
    title: 'Kalkyl och mängdförteckning Linköping',
    description: 'Linköpings kommun behöver konsultstöd för framtagande av kalkyl och mängdförteckning inför upphandling av totalentreprenad för nytt kulturhus. Inkluderar kostnadsberäkning i alla skeden.',
    category: 'kalkyl',
    region: 'Linköping',
    buyer: 'Linköpings kommun',
    value: 500000,
    currency: 'SEK',
    publishedAt: new Date(Date.now()),
    deadlineAt: new Date(Date.now() + 18 * 86400000),
    source: 'visma_anbud',
    sourceUrl: 'https://vismaanbud.com/mock/009',
    rawData: { referenceNumber: 'VA-2024-9012' },
  },
  {
    externalId: 'MOCK-010',
    title: 'Entreprenadjuridisk rådgivning — Trafikverket',
    description: 'Trafikverket upphandlar ramavtal för entreprenadjuridisk rådgivning. Uppdraget omfattar tvistlösning, kontraktsgenomgångar och stöd vid ÄTA-hantering i infrastrukturprojekt.',
    category: 'entreprenadjuridik',
    region: 'Hela Sverige',
    buyer: 'Trafikverket',
    value: 5000000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 6 * 86400000),
    deadlineAt: new Date(Date.now() + 10 * 86400000),
    source: 'ted_eu',
    sourceUrl: 'https://ted.europa.eu/mock/010',
    rawData: { tedReference: '2024/S 060-789012', framework: true },
  },
  {
    externalId: 'MOCK-011',
    title: 'Teknisk förvaltning bostadsbestånd Jönköping',
    description: 'Jönköpings Bostads AB söker partner för teknisk förvaltning av ca 3000 lägenheter. Inkluderar felanmälanshantering, underhållsplanering, energioptimering och löpande drift.',
    category: 'teknisk_förvaltning',
    region: 'Jönköping',
    buyer: 'Jönköpings Bostads AB',
    value: 15000000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 2 * 86400000),
    deadlineAt: new Date(Date.now() + 22 * 86400000),
    source: 'mercell',
    sourceUrl: 'https://mercell.com/mock/011',
    rawData: { cpvCode: '70332000', units: 3000 },
  },
  {
    externalId: 'MOCK-012',
    title: 'Fastighetsutveckling blandstad Örebro',
    description: 'ÖrebroBostäder AB söker strategisk rådgivare för fastighetsutveckling i Södra Ladugårdsängen. Projektet omfattar ca 500 bostäder, lokaler och allmänna ytor. Uppdraget inkluderar marknadsanalys, konceptutveckling och ekonomisk modellering.',
    category: 'fastighetsutveckling',
    region: 'Örebro',
    buyer: 'ÖrebroBostäder AB',
    value: 2000000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 3 * 86400000),
    deadlineAt: new Date(Date.now() + 14 * 86400000),
    source: 'visma_anbud',
    sourceUrl: 'https://vismaanbud.com/mock/012',
    rawData: { referenceNumber: 'VA-2024-3456' },
  },
  {
    externalId: 'MOCK-013',
    title: 'Underhållsplan för kommunala fastigheter Umeå',
    description: 'Umeå kommun upphandlar konsulttjänst för framtagande av underhållsplaner för kommunens fastighetsbestånd om ca 200 byggnader. Inkluderar statusbesiktning, livscykelkostnadsanalys och prioritering.',
    category: 'underhåll',
    region: 'Umeå',
    buyer: 'Umeå kommun',
    value: 900000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 8 * 86400000),
    deadlineAt: new Date(Date.now() + 6 * 86400000),
    source: 'mercell',
    sourceUrl: 'https://mercell.com/mock/013',
    rawData: { cpvCode: '71315000', buildings: 200 },
  },
  {
    externalId: 'MOCK-014',
    title: 'Byggkontroll nybyggnad kontor Sundsvall',
    description: 'Sundsvalls kommun söker byggkontrollant för nybyggnad av kommunhus. Uppdraget omfattar kontroll av utförande, materialval och kvalitetssäkring. Kräver behörighet enligt PBL.',
    category: 'byggkontroll',
    region: 'Sundsvall',
    buyer: 'Sundsvalls kommun',
    value: 700000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 1 * 86400000),
    deadlineAt: new Date(Date.now() + 2 * 86400000),
    source: 'visma_anbud',
    sourceUrl: 'https://vismaanbud.com/mock/014',
    rawData: { referenceNumber: 'VA-2024-7890' },
  },
  {
    externalId: 'MOCK-015',
    title: 'Projektledning infrastrukturprojekt Luleå',
    description: 'Luleå kommun söker projektledare för samhällsbyggnadsprojekt kopplat till ny stadsdel. Uppdraget omfattar projektledning för gator, VA, park och belysning med totalbudget ca 250 Mkr.',
    category: 'projektledning',
    region: 'Luleå',
    buyer: 'Luleå kommun',
    value: 6000000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 4 * 86400000),
    deadlineAt: new Date(Date.now() + 35 * 86400000),
    source: 'ted_eu',
    sourceUrl: 'https://ted.europa.eu/mock/015',
    rawData: { tedReference: '2024/S 070-345678', budget: 250000000 },
  },
  {
    externalId: 'MOCK-016',
    title: 'Byggprojektledning sjukvårdsbyggnad Karlstad',
    description: 'Region Värmland upphandlar byggprojektledare för renovering och om-/tillbyggnad av centralsjukhuset i Karlstad. Projektet har en budget på 1,2 miljarder SEK och pågår i 5 år.',
    category: 'byggprojektledning',
    region: 'Karlstad',
    buyer: 'Region Värmland',
    value: 9500000,
    currency: 'SEK',
    publishedAt: new Date(Date.now() - 10 * 86400000),
    deadlineAt: new Date(Date.now() + 45 * 86400000),
    source: 'mercell',
    sourceUrl: 'https://mercell.com/mock/016',
    rawData: { cpvCode: '71541000', projectBudget: 1200000000 },
  },
];

export class MockTenderSource implements TenderSource {
  name = 'mock';

  async fetch(): Promise<RawTender[]> {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 100));
    return MOCK_TENDERS;
  }
}
